modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/EccentricVamp/Shrunk/issues"

[[mods]]
modId = "shrunk"
version = "${version}"
displayName = "Shrunk"
displayURL = "https://github.com/EccentricVamp/Shrunk"
authors = "EccentricVamp"
description = '''Honey, I shrunk the player'''

[[dependencies.shrunk]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrunk]]
modId = "pehkui"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "SERVER"
