modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/EccentricVamp/Shrunk/issues"
[[mods]]
modId="shrunk"
version="${file.jarVersion}"
displayName="Shrunk"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="shrunk.png" #optional
credits="Thanks for this example mod goes to Java"
authors="EccentricVamp"
description='''
Why is this mandatory?
'''
[[dependencies.shrunk]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shrunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shrunk]]
    modId="pehkui"
    mandatory=true
    versionRange="3.1.0"
    ordering="NONE"
    side="BOTH"
