modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/EccentricVamp/Shrunk/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Shrunk"
displayURL = "https://github.com/EccentricVamp/Shrunk"
authors = "${mod_author}"
description = '''Honey, I shrunk the player'''

[[dependencies.shrunk]]
modId = "forge"
mandatory = true
versionRange = "[43.1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shrunk]]
modId = "pehkui"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "SERVER"
